### PR TITLE
Upgrade `golang.org/x/tools` to latest version

### LINKED ISSUE #31: package imported without types errors when using with Go 1.18
When using this tool with Go 1.18, I'm seeing errors like
```
faillint: internal error: package "time" without types was imported from "github.com/github/my-project-repo/constants"
```

This might be fixed by bumping `golang.org/x/tools` to a newer version

### PR DESCRIPTION
**Pull request by joshmgross**
Attempting to fix #31 by upgrading `golang.org/x/tools` to a version that supports Go 1.18

### CODE REVIEW

**Comment by joshmgross** [comment]
Confirmed this fixed the issues I was seeing when using `faillint` built from https://github.com/joshmgross/faillint/tree/joshmgross/upgrade-tools

**Comment by aybabtme** [comment]
👍 thanks @joshmgross

**Comment by fatih** [comment]
Thank you @joshmgross

**Comment by fatih** [comment]
I released a new version: https://github.com/fatih/faillint/releases/tag/v1.9.0

**Pull request merged**
